services:

  server:
    image: ${PLSQL_IMAGE}
    container_name: server
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - ./dbfiles:/var/lib/postgresql/data
    networks:
      - local

  pgadmin:
    image: ${PGADMIN_IMAGE}
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      server:
        condition: service_started
    networks:
      - local
      
networks:
  local:
    driver: bridge
    name: $NETWORK
