version: '3.4'

services:

  # The MQTT Server
  mosquitto-server:
    image: eclipse-mosquitto:2.0.14
    container_name: ${MOSQUITTO_CONTAINER}
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - local

  # Mock IOT device
  mock-device:
    image: ${DEVICE_IMAGE_NAME}
    container_name: ${MOCK_DEVICE_CONTAINER}
    command: /${CLIENT_APP_NAME}
    networks:
      - local

  # Mock backend to process payload from device
  mock-devproc:
    image: ${DEVPROC_IMAGE_NAME}
    container_name: ${MOCK_DEVPROC_CONTAINER}
    command: /${CLIENT_APP_NAME}
    networks:
      - local

networks:
  local:
    name: ${NETWORK_NAME}